services:
  postgres:
    image: postgres:17-alpine
    container_name: examen_postgres
    restart: always
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devops_user -d devops_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: examen_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: devops-flask-postgres:2.0.0
    container_name: examen_flask_app
    restart: always
    environment:
      APP_NAME: "Examen DevOps Flask"
      APP_VERSION: "2.0.0"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: devops_db
      DB_USER: devops_user
      DB_PASSWORD: devops_pass
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
